[plugin]
repository = "https://github.com/attickdoor/XIVComboPlugin.git"

# The commit to check out and build from the repository.
commit = "53f61f00e4f609e53c98a98eee4137c509c7f28d"

# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "attickdoor"
]

# Optional: where your project/csproj is located within the repository.
# If empty or unspecified, it will be assumed the project is in the root of the repository.
project_path = "XIVComboPlugin"

# The changelog for this version. Will be shown in-game, as well on the Goat Place Discord.
changelog = """\
		7.1
		"""
